//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractivePPT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InteractivePPT.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access code.
        /// </summary>
        internal static string access_code {
            get {
                return ResourceManager.GetString("access_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add artifact(s).
        /// </summary>
        internal static string add_artifact {
            get {
                return ResourceManager.GetString("add_artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to next slide.
        /// </summary>
        internal static string add_to_next_slide {
            get {
                return ResourceManager.GetString("add_to_next_slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will now shut down...
        /// </summary>
        internal static string application_will_shut_down {
            get {
                return ResourceManager.GetString("application_will_shut_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact&apos;s location:.
        /// </summary>
        internal static string artifact_location {
            get {
                return ResourceManager.GetString("artifact_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there isn&apos;t any chart with question name &quot;{0}&quot; of selected chart type. Go to slide in front of which you want to add new slide with chart, choose in application option &quot;add to next slide&quot; for artifact location and again click on button for adding artifact(s).
        /// </summary>
        internal static string chart_for_selected_question_doesnt_exist_message {
            get {
                return ResourceManager.GetString("chart_for_selected_question_doesnt_exist_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart for selected question doesn&apos;t exist in this presentation.
        /// </summary>
        internal static string chart_for_selected_question_doesnt_exist_title {
            get {
                return ResourceManager.GetString("chart_for_selected_question_doesnt_exist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart type:.
        /// </summary>
        internal static string chart_type {
            get {
                return ResourceManager.GetString("chart_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In selected directory already exists presentation with same name. Choose &quot;Yes&quot; option if you want to override local version with remote one, &quot;No&quot; option if you want to override remote version with local one or &quot;Cancel&quot; if you just want to open local version without overriding remote one.
        /// </summary>
        internal static string collision_between_presentations_message {
            get {
                return ResourceManager.GetString("collision_between_presentations_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer version of presentation possibly available.
        /// </summary>
        internal static string collision_between_presentations_title {
            get {
                return ResourceManager.GetString("collision_between_presentations_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment filtering.
        /// </summary>
        internal static string comment_filtering {
            get {
                return ResourceManager.GetString("comment_filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there isn&apos;t any slide with comments with question name &quot;{0}&quot;. Go to slide in front of which you want to add new slide with comments, choose in application option &quot;add to next slide&quot; for artifact location and again click on button for adding artifact(s).
        /// </summary>
        internal static string comments_for_selected_question_doesnt_exist_message {
            get {
                return ResourceManager.GetString("comments_for_selected_question_doesnt_exist_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments for selected question don&apos;t exist in this presentation.
        /// </summary>
        internal static string comments_for_selected_question_doesnt_exist_title {
            get {
                return ResourceManager.GetString("comments_for_selected_question_doesnt_exist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with server-side of this application could not be established!.
        /// </summary>
        internal static string communication_with_server_not_established {
            get {
                return ResourceManager.GetString("communication_with_server_not_established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://m.facebook.com/a/language.php?l=en_US&amp;lref=https%3A%2F%2Fm.facebook.com%2Flogin%2F%3Fref%3Ddbl%26fl%26refid%3D8%26refsrc%3Dhttps%253A%252F%252Fm.facebook.com%252Flogin%252F%253Fref%253Ddbl&amp;gfid=AQDyMwI6AfNsokSb&amp;ref=dbl.
        /// </summary>
        internal static string fb_login_url {
            get {
                return ResourceManager.GetString("fb_login_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group others:.
        /// </summary>
        internal static string group_remaining_options {
            get {
                return ResourceManager.GetString("group_remaining_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to presentation.
        /// </summary>
        internal static string link_to_presentation {
            get {
                return ResourceManager.GetString("link_to_presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message content.
        /// </summary>
        internal static string message_content {
            get {
                return ResourceManager.GetString("message_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems like you&apos;ve never used mobile version of this application before!.
        /// </summary>
        internal static string mobile_app_not_used_before {
            get {
                return ResourceManager.GetString("mobile_app_not_used_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My presentations.
        /// </summary>
        internal static string my_presentations {
            get {
                return ResourceManager.GetString("my_presentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num of options to show (0...all):.
        /// </summary>
        internal static string number_of_options_to_show {
            get {
                return ResourceManager.GetString("number_of_options_to_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open presentation.
        /// </summary>
        internal static string open_presentation {
            get {
                return ResourceManager.GetString("open_presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string other_options {
            get {
                return ResourceManager.GetString("other_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select shorter path because length of chosen one (including name of file that should be stored in it) exceeds 255 characters!.
        /// </summary>
        internal static string path_too_long {
            get {
                return ResourceManager.GetString("path_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation management.
        /// </summary>
        internal static string presentation_management {
            get {
                return ResourceManager.GetString("presentation_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation name.
        /// </summary>
        internal static string presentation_name {
            get {
                return ResourceManager.GetString("presentation_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while trying to override previous presentation on remote server.
        /// </summary>
        internal static string problem_with_overriding_remote_presentation {
            get {
                return ResourceManager.GetString("problem_with_overriding_remote_presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        internal static string proceed {
            get {
                return ResourceManager.GetString("proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qr code.
        /// </summary>
        internal static string qr_code {
            get {
                return ResourceManager.GetString("qr_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        internal static string refresh_presentation_list {
            get {
                return ResourceManager.GetString("refresh_presentation_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace existing artifact.
        /// </summary>
        internal static string replace_existing_artifact {
            get {
                return ResourceManager.GetString("replace_existing_artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply-requests.
        /// </summary>
        internal static string reply_requests {
            get {
                return ResourceManager.GetString("reply_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred on the server-side while trying to start audience listener for your presentation! Try again later or contact server&apos;s administrator.
        /// </summary>
        internal static string server_listener_not_instantiated {
            get {
                return ResourceManager.GetString("server_listener_not_instantiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey:.
        /// </summary>
        internal static string survey {
            get {
                return ResourceManager.GetString("survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string user_id {
            get {
                return ResourceManager.GetString("user_id", resourceCulture);
            }
        }
    }
}
